// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MacroUsage } from "./MacroUsage";

export type DeriveMacroUsage = { count: number, avg: number, derives: MacroUsage, };
