// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeriveUsage = { avg: number, median: number, mode: Array<number>, max: number, sorted_data: Array<number>, };
