// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeriveMacroUsage } from "./DeriveMacroUsage";
import type { MacroUsage } from "./MacroUsage";

export type MacroAnalyzis = { attribute_macro_definitions: MacroUsage, declarative_macro_definitions: MacroUsage, procedural_macro_definitions: MacroUsage, derive_macro_definitions: MacroUsage, derive_macro_usage: DeriveMacroUsage, attribute_macro_invocations: MacroUsage, builtin_attribute_macro_invocations: MacroUsage, macro_invocations: MacroUsage, };
