// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrateAnalyzis } from "./CrateAnalyzis";
import type { RepoAnalyzis } from "./RepoAnalyzis";

export type AnalyzisResults = { crates: { [key: string]: CrateAnalyzis }, repos: { [key: string]: RepoAnalyzis }, };
