// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharLineCount } from "./CharLineCount";
import type { MacroAnalyzis } from "./MacroAnalyzis";

export type CrateAnalyzis = { source_count: CharLineCount | null, expanded_count: { Ok : CharLineCount } | { Err : string } | null, macro_usage: MacroAnalyzis | null, };
